# Generated by Django 4.2.5 on 2023-11-18 23:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_rename_post_publication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='Post',
        ),
    ]
